### ISSUE TITLE
Cannot listen for ESC key

### ISSUE THREAD

**Issue by koso00** [clue/reactphp-stdio#90]
I'm unable to listen for ESC key escape code, how do i do that?

**Comment by clue** [comment]
Hi @koso00, excellent question - and there's no easy answer unfortunately.

The <kbd>esc</kbd> key will emit `0x1b` hex code, so you could technically bind to this code. However, the problem is that all escape sequences always start with this exact code, so it is currently assumed to be part of an escape sequence and will never be emitted on its own. For example, the <kbd>left</kbd> key will emit the sequence `0x1b 0x5b 0x44`, so there's no way to discern the first byte from an actual <kbd>esc</kbd> key press.

As a work around, you may either bind to any other key or a C1 sequence that starts with the <kbd>esc</kbd> key. For example, if you hit this key twice, you can bind to `0x1b 0x1b`.

I'm not sure how we could solve this, but I think we would have to address this upstream: https://github.com/clue/reactphp-term/blob/3cec1164073455a85a3f2b3c3fe6db2170d21c2a/src/ControlCodeParser.php#L131
